### ISSUE TITLE
Getting types of an entity

### ISSUE THREAD

**Issue by lugy2001** [MakoLab/RomanticWeb#56]
Is it possible to get the used Interfaces of an entity?

entity.GetTypes() returns only the RDF-Types but not the used C#-Interfaces. I don't know how to retrieve the Interfaces from that URIs. Is it somehow possible?

**Comment by tpluscode** [comment]
Have a look at [Mapping.Extensions](https://github.com/MakoLab/RomanticWeb/blob/master/RomanticWeb/Mapping/Extensions.cs) class. Does it contain a method you need?

**Comment by lugy2001** [comment]
No there is no method to get Interfaces when I have RDF-Types as URIs.

Alternatively there could be a method in EntityExtensions parallel to ```IEnumerable<EntityId> GetTypes(this IEntity entity)``` (which basicly returns RDF-Types as URIs) like ```IEnumerable<Type> GetInterfaces(this IEntity entity)``` or similar.
