### ISSUE TITLE
Project files are un-openable.

### ISSUE THREAD

**Issue by Jestar342** [MakoLab/RomanticWeb#58]
C:\git\RomanticWeb\RomanticWeb\RomanticWeb.csproj : error  : The project file 'RomanticWeb' cannot be opened.

The <TargetFrameworkIdentifier> for a portable project must be '.NETPortable'.

**Comment by alien-mcl** [comment]
I assume you're opening it with VS2013 or newer. Indeed things changed with multi-platform .net projects between VS2012 and 2013. Either use the an older VS or just remove 786C830F-07A1-408B-BD7F-6EE04809D6DB from the csproj file ProjectTypeGuids node - this should "downgrade" it to ordinary C# library project,
We need to think it over how to deal with this in future

**Comment by alien-mcl** [comment]
I understand that everything is clear now - please let me close that one.
