### ISSUE TITLE
Strings disappear when changing context's CurentCulture

### ISSUE THREAD

**Issue by wk-pl** [MakoLab/RomanticWeb#61]
Hi,
I have encountered a strange behaviour of RomanticWeb, when working with data of different languages. I have an IAddress interface, containing some traditional address fields (i.e. City, PostalCode, StreetAddress - all strings) and some Uri fields (most notably - Country). I am creating the IAddress entity based upon xml-parsed data, which includes other data than the address alone and for some data - the language is specified.

By default the RW ontext uses the InvariantCulture as it's CurrentCulture, but when I create an addres which is marked as lang="fr" I need to change the CurrentCulture to the french culture, then create the address and fill all neccessary fields. When I change the context's CurrentCulture back to the default, all the string fields in the reated address turns to null. What should I do for the values to persist the context's culture change?

I'm pasting the code I'm using for clarification: (the Address is the type of an object created from parsing xml data)

```

private static IAddress ToAddress(this Address address, IEntityContext entityContext, Uri identifier)
{
    var defaultCultureInfo = entityContext.CurrentCulture;
    var result = entityContext.Create<IAddress>(new EntityId(identifier));
    SetCultureInfo(entityContext, address.Language);
    result.StreetAddress = address.StreetAddress;
    result.City = address.City;
    result.Country = address.ToCountry(entityContext);
    result.PostalCode = address.PostalCode;
    entityContext.CurrentCulture = defaultCultureInfo; //here, when I look at the City, PostalCode
                                                       and StreetAddress fields of result, they 
                                                       are all null
    return result;
}

private static CultureInfo SetCultureInfo(IEntityContext context, string language)
{
    CultureInfo targetLanguage = null;
    if (!String.IsNullOrEmpty(language))
    {
        try
        {
            targetLanguage = CultureInfo.GetCultureInfo(language);
        }
        catch
        {
        }
    }

    if (targetLanguage == null)
    {
        return null;
    }

    var result = context.CurrentCulture;
    context.CurrentCulture = targetLanguage;
    return result;
}

```

Any thoughts/hints?

**Comment by alien-mcl** [comment]
This behavior is as designed. Please notice that invariant culture is a fallback for French, but not the opposite.
By setting literals in French you do store them in the underlying RDF graph - switching back to invariant does not loose these data (if it does - give me a shout!). The thing is that once switched, RW does not find any matching literals - it cannot use those you set as french is not invariant's fallback. Imagine you have also English or Chineese - which should be used in that situation?
Please set literals in invariant and/or some specific culture to feed RDF with more language options. Then in your application, say web page browsed in French, RW will look for literals in that language, and if it fails it'll try to fallback to invariant.

Hope it helps.

**Comment by alien-mcl** [comment]
I understand that everything is clear now - please let me close that one.

**Comment by wk-pl** [comment]
Sorry, I didn't have enough time this week to check everything as needed, but I was quite sure those strings were loosened definitely - I'm gonna make sure this first thing in the morning on monday and let you know.

**Comment by wk-pl** [comment]
I double checked and the data does not get nulled permanently (if I change back to the culture the data was created in, the strings there again).

There again, I cannot easily compare two objects (one created via an RW context and one retrieved by another RW persistent context) - I would need to compare the string fields after switching both contexts' cultures to the cultures under which those fields were filled, but the compared objects do not have such information :/ 

I probably would be able to compare those objects if I could get the quads/triples generating the objects, but I guess I'm using RW not to play with the triples themselves.

Any hints here?

**Comment by alien-mcl** [comment]
Well, indeed comparing two instances is a tricky one. Equals will try to compare identifiers, thus this is not what you want. I think this doesn't leave you any option other than comparing properties you need. You may wan't to have an extension method that will do that for you.
Any way, you can still use _Cultures_ property of the _IEntityContext_ - it'll get all _CultureInfo_ used in all literals in currently loaded triples - you could iterate all of those cultures and compare properties.
You can always try using _Store_ property of the _IEntityContext_ to get the triples loaded in the context.
