### ISSUE TITLE
Changing type (types) of entities without changing EntityId

### ISSUE THREAD

**Issue by wk-pl** [MakoLab/RomanticWeb#62]
Hi,

I've come up with a problem when trying to change the type of a certain entity. I have two interfaces IAddress and IBaseAddress (the IAddress implements IBaseAddress).

```
[Class("IBaseAddress_type")]
public interface IBaseAddress : RomanticWeb.Entities.IEntity
{
    public string Field1 { get; set; }
    public string Field2 { get; set; }
}

[Class("IAddress_type")]
public interface IAddress : IBaseAddress
{
    public string Field3 { get; set; }
    public string Field4 { get; set; }
}
```

In an application I have also an entity which holds a collection od IBaseAddress items and I am adding some IAddress items to the collection. In time however I need to change some items so that they retain only their IBaseAddresses properties. I manage to nullify all properties, however when I look at the triples in the triple store, all the items in the collection still have the both type triples:
```
<Item_Uri> a <IBaseAddress_type_uri> , <IAddress_type_uri> .
```
I can achieve this only if I remove the desired items from the collection and add new items with **new** entity id's.

Can it be done without having have to alter the id's? In a single commit?

Best

**Comment by alien-mcl** [comment]
Well - this behavior seems to work as expected. Nullyfing properties won't change the fact that given entity os of some type. It'll just remove those statements mapped to the nullyfied properties.
I think solution you seek requires you to _undo_ a statement that a given entity is of some type. You could cast your entity to _ITypedEntity_ which exposes a list of types a given entity has in it's _rdf:type_ statements.
You could remove the ones that you don't want enymore.
I was just wondering - if an entity was considered to be of type _A_, why in time it ceased to be of that type? I feel some logical discrepancy here.

**Comment by wk-pl** [comment]
Yeah, I suspected it worked as expected. :P
Just couldn't find a way to detach the unneeded type. Using the ITypedEntity works like a charm! Thanks!

As to your question - the collection would hold all changes made to addresses in time. The current address needs to be described by additional fields, which cannot be present in the older address versions.

Thx again for your help! :)

**Comment by wk-pl** [comment]
Stumbled upon something new - iterating through the collection of those addresses takes some very long time (even a couple of seconds with only a single item in the collection), when the entity is retrieved from a graph db with RomanticWeb. When I create the same entity (before committing it to db) I can view the collection, iterate through back and forth in just a blink of an eye. During debugging I'm getting an evaluation time out when trying to look at the collection.

Any idea what could be the case here?

**Comment by alien-mcl** [comment]
I'd need some more details. From this brief it looks like it takes some time to gather triples from the underlying triple store. Few things to check:
* poor triple store performance or issues with connection pooling
* large number of triples per graph; in general there is a INamedGraphSelector used to trim which graphs / triples to retrieved
What kind of triple store sits there? What is the data set?

**Comment by wk-pl** [comment]
Took me some time to respond, sorry.

Actually it must have been some connection/performance issues as you mentioned - the next day everything worked swiftly. 
Additionally, the graphs retrieved were no larger than 60-70 triples so I didn't think it was much at all.

Most importantly, thanks again for your help. Everything works fine :)
I think the issue can be closed :)

**Comment by alien-mcl** [comment]
Glad to hear thad. Indeed 60-70 triples is a tiny graph.

I'm closing this issue.
