### ISSUE TITLE
Mapping entities from graph

### ISSUE THREAD

**Issue by wk-pl** [MakoLab/RomanticWeb#71]
Hi,

I have been trying to map an rdf graph (dotNetRdf IGraph) to an object using RW. I managed to do this by writing an extension method, where I create an entity context factory supplying a triple store instance (.WithDotNetRdf(ITripleStore store)) containing the mentioned graph. I have added the meta graph with generated meta graph triple into the store as well.
This approach works to the extent that it actually maps the graph to the object, but the problem I encounter is efficiency as I need to create a factory each time I try to map graphs and this is time consuming.

My current code looks something like this:
    
        /// <summary>Maps a given graph to object.</summary>
        /// <typeparam name="T">Type of the mapped object.</typeparam>
        /// <param name="graph">Source graph.</param>
        /// <param name="namedGraphSelector">Named graph selector.</param>
        /// <param name="metaGraphUri">Meta graph uri.</param>
        /// <returns>Mapped object.</returns>
        public static T MapToEntity<T>(this IGraph graph, INamedGraphSelector namedGraphSelector, Uri metaGraphUri) where T : class, IEntity
        {
            ITripleStore store = new TripleStore();
            store.Add(graph);

            store.Add(GenerateMetaGraph(graph.BaseUri, graph.BaseUri, metaGraphUri));

            var contextFactory = new EntityContextFactory()
                .WithMappings((MappingBuilder builder) => builder.FromAssemblyOf<ISomeInterface>())
                .WithDefaultOntologies()
                .WithNamedGraphSelector(namedGraphSelector)
                .WithMetaGraphUri(metaGraphUri)
                .WithDotNetRDF(store);

            var entity = contextFactory.CreateContext().Load<T>(new EntityId(recordUri));
            return entity;
        }
    
Is there a way of switching the underlying triple store before creating the actual context without the need to create the whole context factory? Or is there another way of solely mapping a dotNetRdf graph to an object using RW?

**Comment by alien-mcl** [comment]
Well - indeed creating a factory is time consuming. I don't think there is anything we can do about it.
Could you please elaborate more on what you would like to achieve?
Generally speaking - factory would need a triple store to wrap around, but mappings are not related to any specific graph - it could be possible to pass an ITripleStore which could then use some inner logic to switch between actual stores. Again - I'd need some more details on what you would like to achieve.

**Comment by wk-pl** [comment]
I'm recieving IGraph objects from an external library and need to map their contents to my objects. Because the amount of graphs recieved is large and i need to do some operations on each of the graphs I would like to map the graph to an object, process any operations neccessary on the object and generate a new graph after changes to the object is made. Then I need to send the resulting graph back to the other library.
Due to the number of graphs processed I would require a faster method to map the incoming graphs to objects. I tried to create the factory with an empty in memory triple store and then, as I recieve the graph tried to inject another triple store like this:
````
var tripleStore = MethodGeneratingTripleStoreFromSourceGraph(sourceGraph);
var context = someContextFactory.Value.WithDotNetRDF(tripleStore).CreateContext();
EntityId objectId = MethodRetrievingObjectUriFromSourceGraphUri(sourceGraph.BaseUri);
var myObject = context.Load<ISomeInterface>(objectId);
````
This however didn't create a context with uderlaying generated triple store, but with the empty triple store passed to the factory upon creating the factory itself and thus the "myObject" variable had all fields null. Everything works fine when I create the entire factory and pass the generated triple store, but it takes too much time for the whole app to work efficiently.

Any ideas what can be done about it?

**Comment by alien-mcl** [comment]
Can't you create one triple store (either built in TripleStore or own ITripleStore implementation) and add obtained IGraph instances to that triple store?
Generally - factory was bound to the triple store by design. I think this is quite common in ORM class solutions. You cannot switch between i.e. databases within single context in EF. Still, you have that extra abstraction layer in ITripleStore that you could leverage for your needs in this scenario.

**Comment by wk-pl** [comment]
Tried to create one triple store and adding new graphs and it works fine. Thx.

Just needed to recycle the triple store and the entire context factory when too much memory is being consumed.

Thx again for the advice!

**Comment by alien-mcl** [comment]
Good to hear that.
As for the memory footprint - indeed RDF may be memory consuming. Unfortunately, dotNetRDF in-memory triple store has some issues with performance while querying with SPARQL.

Anyway, I think we can close that one.
